export const REQ_ADDRESS = 'reqaddress'
export const REQ_CATEGORYS = 'reqcategorys'
export const REQ_SHOPS = 'reqshops'
export const SAVEUSER = 'saveuser'
export const SAVRTOKEN = 'savetoken'
export const RESET_USER = 'reset_user'
export const RESET_TOKEN = 'reset_token'